from typing import Self
import numpy as np


class Wdotool:
    def __init__(self, wayland_display: str | None  = None) -> Self:...
    def move_mouse(self, x_extent: int, y_extent: int, x: int, y: int, x_max: int | None  = None, y_max: int | None  = None) -> None:...
    def left_click(self, duration_ms: int, duration_ms_max: int | None  = None) -> None: ...
    def right_click(self, duration_ms: int, duration_ms_max: int | None  = None) -> None: ...
    def key_press(self, key: int, duration_ms: int, duration_ms_max: int | None  = None) -> None: ...
    def screenshot(self, screen_name: str | None  = None) -> np.ndarray: ...
